### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by alexanderbartels** [alexanderbartels/mushroom#5]
Add simple configuration file with default name ".mushroom.yml" 
Default search path and configureable path over command line argument.. 
`mushroom -config ./confg/meineConfig.yml`

``` yml

image-provider:
   - type: file
   - location: ./images/

cache-header:
   - must-revalidate // schlechtes beispiel

...
```
